apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: custom-azurefile-csi
  resources:
    requests:
      storage: 5120Gi

---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: shared
spec: {}
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile
  namespace: shared
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: custom-azurefile-csi
  resources:
    requests:
      storage: 5120Gi

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: default
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - mountPath: "/mnt/azurefile/"
        name: vol
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: my-azurefile
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: shared
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - mountPath: "/mnt/azurefile/"
        name: vol
        readOnly: true
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: my-azurefile
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}   