apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        aadpodidbinding: aks-spot-mi
    spec:
      nodeSelector:
        "kubernetes.io/os": "linux"
        "kubernetes.azure.com/scalesetpriority": "spot"
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
  selector:
    matchLabels:
      app: nginx
